/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppSendRouteImport } from './routes/_app/send'
import { Route as AppQrRouteImport } from './routes/_app/qr'
import { Route as AppProfileRouteImport } from './routes/_app/profile'
import { Route as AppHomeRouteImport } from './routes/_app/home'
import { Route as AppHistoryRouteImport } from './routes/_app/history'
import { Route as AppAgentRouteImport } from './routes/_app/agent'
import { Route as AppAdminRouteImport } from './routes/_app/admin'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSendRoute = AppSendRouteImport.update({
  id: '/send',
  path: '/send',
  getParentRoute: () => AppRoute,
} as any)
const AppQrRoute = AppQrRouteImport.update({
  id: '/qr',
  path: '/qr',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppHomeRoute = AppHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => AppRoute,
} as any)
const AppHistoryRoute = AppHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => AppRoute,
} as any)
const AppAgentRoute = AppAgentRouteImport.update({
  id: '/agent',
  path: '/agent',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminRoute = AppAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admin': typeof AppAdminRoute
  '/agent': typeof AppAgentRoute
  '/history': typeof AppHistoryRoute
  '/home': typeof AppHomeRoute
  '/profile': typeof AppProfileRoute
  '/qr': typeof AppQrRoute
  '/send': typeof AppSendRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admin': typeof AppAdminRoute
  '/agent': typeof AppAgentRoute
  '/history': typeof AppHistoryRoute
  '/home': typeof AppHomeRoute
  '/profile': typeof AppProfileRoute
  '/qr': typeof AppQrRoute
  '/send': typeof AppSendRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/_app/admin': typeof AppAdminRoute
  '/_app/agent': typeof AppAgentRoute
  '/_app/history': typeof AppHistoryRoute
  '/_app/home': typeof AppHomeRoute
  '/_app/profile': typeof AppProfileRoute
  '/_app/qr': typeof AppQrRoute
  '/_app/send': typeof AppSendRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/admin'
    | '/agent'
    | '/history'
    | '/home'
    | '/profile'
    | '/qr'
    | '/send'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/admin'
    | '/agent'
    | '/history'
    | '/home'
    | '/profile'
    | '/qr'
    | '/send'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/auth'
    | '/_app/admin'
    | '/_app/agent'
    | '/_app/history'
    | '/_app/home'
    | '/_app/profile'
    | '/_app/qr'
    | '/_app/send'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/send': {
      id: '/_app/send'
      path: '/send'
      fullPath: '/send'
      preLoaderRoute: typeof AppSendRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/qr': {
      id: '/_app/qr'
      path: '/qr'
      fullPath: '/qr'
      preLoaderRoute: typeof AppQrRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/profile': {
      id: '/_app/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/home': {
      id: '/_app/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof AppHomeRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/history': {
      id: '/_app/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof AppHistoryRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/agent': {
      id: '/_app/agent'
      path: '/agent'
      fullPath: '/agent'
      preLoaderRoute: typeof AppAgentRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin': {
      id: '/_app/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AppAdminRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAdminRoute: typeof AppAdminRoute
  AppAgentRoute: typeof AppAgentRoute
  AppHistoryRoute: typeof AppHistoryRoute
  AppHomeRoute: typeof AppHomeRoute
  AppProfileRoute: typeof AppProfileRoute
  AppQrRoute: typeof AppQrRoute
  AppSendRoute: typeof AppSendRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAdminRoute: AppAdminRoute,
  AppAgentRoute: AppAgentRoute,
  AppHistoryRoute: AppHistoryRoute,
  AppHomeRoute: AppHomeRoute,
  AppProfileRoute: AppProfileRoute,
  AppQrRoute: AppQrRoute,
  AppSendRoute: AppSendRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
